"""Shared utilities, typing helpers, metrics, and seeding helpers live here."""

from .air_defense_v1_metrics import (
    DEFAULT_HIGH_THREAT_THRESHOLD,
    DIAGNOSTIC_AGGREGATE_METRICS,
    AirDefenseV1DiagnosticsTracker,
    aggregate_air_defense_v1_episode_metrics,
)
from .air_defense_v1_decision_metrics import (
    LEAK_ATTRIBUTION_CATEGORIES,
    AirDefenseV1DecisionTracker,
    aggregate_decision_rows,
    aggregate_collapsed_unit_counts,
    aggregate_leak_attributions,
    classify_high_threat_leak,
    validate_unit_order,
)
from .policy_probe import (
    PolicyProbeCorpus,
    evaluate_policy_probe,
    make_policy_probe_corpus,
)
from .ppo_training_diagnostics import PPOTrainingDiagnosticsCallback
from .task13_diagnostics import (
    binary_calibration_metrics,
    engagement_threshold_grid,
    hierarchical_counterfactual_advantages,
    one_step_td_error,
)
from .q_critic_diagnostics import (
    engagement_sign_accuracy,
    grouped_state_split,
    pairwise_ranking_accuracy,
    regression_metrics,
    top_action_accuracy,
)
from .q_critic_training import (
    action_group_ids,
    build_pairwise_training_data,
    center_by_group,
    integer_group_codes,
    q_critic_training_loss,
    validation_difference_score,
)
from .hierarchical_q_diagnostics import (
    build_hierarchical_q_data,
    engagement_sign_metrics,
    hierarchical_q_metrics,
)
from .engagement_utility_diagnostics import (
    EngagementUtilityConfig,
    engagement_utility_labels,
    lower_tail_cvar,
    oracle_classification_metrics,
    safety_resource_oracle,
    utility_oracle_metrics,
)
from .critical_engagement_sampling import (
    engagement_criticality_features,
    select_diverse_critical_snapshots,
)
from .balanced_engagement_training import balanced_engagement_loss
from .engagement_boundary_calibration import (
    EngagementBoundaryConfig,
    EngagementBoundaryConstraints,
    apply_engagement_boundary,
    calibrate_engagement_boundary,
    resource_pressure_from_observations,
    scenario_classification_metrics,
)
from .state_conditioned_value_training import (
    constrained_value_metrics,
    engagement_delta_targets,
    paired_delta_reliability,
    robust_state_conditioned_value_loss,
    scenario_class_balanced_loss,
    state_conditioned_value_loss,
)
from .multibatch_diagnostics import (
    batch_scenario_groups,
    grouped_oracle_metrics,
    leave_one_batch_out_folds,
    minimum_group_class_recall,
)
from .pareto_feasibility import (
    ParetoRecallConstraints,
    audit_pareto_thresholds,
    complete_threshold_candidates,
    pareto_frontier_mask,
    threshold_operating_point,
)
from .independent_confirmation import (
    confirmation_power,
    evaluate_frozen_threshold,
    frozen_thresholds_from_rows,
)
from .cross_batch_calibration import (
    CrossBatchCalibrationConfig,
    FittedCrossBatchCalibrator,
    assemble_calibration_features,
    calibrated_operating_point,
    calibration_candidates,
    equal_block_weights,
    fit_cross_batch_calibrator,
)
from .masked_context_support import MaskedContextSupportIndex
from .boundary_counterfactual_probe import (
    BoundaryCounterfactualProbeConfig,
    BoundaryCounterfactualProbeRunner,
    BoundaryProbeCandidate,
    BoundaryProbeLabels,
    paired_direction_gate,
    select_boundary_candidates,
    select_random_candidates,
)
from .bpce_label_semantics import (
    BPCEAuditContext,
    BPCELabelSemanticsConfig,
    audit_bpce_context,
    collect_bpce_audit_contexts,
    estimate_effect,
    make_bpce_fixed_prefix,
    make_bpce_paired_random_tapes,
    sample_fixed_actions_with_uniforms,
    summarize_bpce_semantics,
)
from .bpce_short_horizon_labels import (
    BPCEShortHorizonConfig,
    BranchTrajectory,
    audit_short_horizon_context,
    classify_component_label,
    component_interval,
    summarize_short_horizon_audit,
    target_event_horizon,
    validate_context_identity,
)
from .action_substitution_opportunity_cost import (
    ActionSubstitutionOpportunityCostConfig,
    OpportunityBranchTrace,
    aggregate_target_rows,
    audit_action_substitution_context,
    intervention_is_unique,
    reliable_positive_opportunity,
    restore_probed_ammo,
    summarize_action_substitution_audit,
)
from .action_substitution_confirmation import (
    ActionSubstitutionConfirmationConfig,
    CostBranchTrace,
    audit_confirmation_context,
    collect_confirmation_contexts,
    grouped_summary_rows,
    summarize_confirmation,
    validate_confirmation_contexts,
)

__all__ = [
    "BoundaryCounterfactualProbeConfig",
    "BoundaryCounterfactualProbeRunner",
    "BoundaryProbeCandidate",
    "BoundaryProbeLabels",
    "BPCEAuditContext",
    "BPCELabelSemanticsConfig",
    "BPCEShortHorizonConfig",
    "BranchTrajectory",
    "DEFAULT_HIGH_THREAT_THRESHOLD",
    "DIAGNOSTIC_AGGREGATE_METRICS",
    "AirDefenseV1DiagnosticsTracker",
    "aggregate_air_defense_v1_episode_metrics",
    "LEAK_ATTRIBUTION_CATEGORIES",
    "AirDefenseV1DecisionTracker",
    "aggregate_decision_rows",
    "aggregate_collapsed_unit_counts",
    "aggregate_leak_attributions",
    "classify_high_threat_leak",
    "validate_unit_order",
    "PolicyProbeCorpus",
    "evaluate_policy_probe",
    "make_policy_probe_corpus",
    "PPOTrainingDiagnosticsCallback",
    "binary_calibration_metrics",
    "engagement_threshold_grid",
    "hierarchical_counterfactual_advantages",
    "one_step_td_error",
    "grouped_state_split",
    "engagement_sign_accuracy",
    "pairwise_ranking_accuracy",
    "regression_metrics",
    "top_action_accuracy",
    "action_group_ids",
    "build_pairwise_training_data",
    "center_by_group",
    "integer_group_codes",
    "q_critic_training_loss",
    "MaskedContextSupportIndex",
    "validation_difference_score",
    "build_hierarchical_q_data",
    "engagement_sign_metrics",
    "hierarchical_q_metrics",
    "EngagementUtilityConfig",
    "engagement_utility_labels",
    "lower_tail_cvar",
    "oracle_classification_metrics",
    "safety_resource_oracle",
    "utility_oracle_metrics",
    "engagement_criticality_features",
    "select_diverse_critical_snapshots",
    "balanced_engagement_loss",
    "EngagementBoundaryConfig",
    "EngagementBoundaryConstraints",
    "apply_engagement_boundary",
    "calibrate_engagement_boundary",
    "resource_pressure_from_observations",
    "scenario_classification_metrics",
    "constrained_value_metrics",
    "engagement_delta_targets",
    "paired_delta_reliability",
    "robust_state_conditioned_value_loss",
    "scenario_class_balanced_loss",
    "state_conditioned_value_loss",
    "batch_scenario_groups",
    "grouped_oracle_metrics",
    "leave_one_batch_out_folds",
    "minimum_group_class_recall",
    "ParetoRecallConstraints",
    "audit_pareto_thresholds",
    "complete_threshold_candidates",
    "pareto_frontier_mask",
    "threshold_operating_point",
    "confirmation_power",
    "evaluate_frozen_threshold",
    "frozen_thresholds_from_rows",
    "CrossBatchCalibrationConfig",
    "FittedCrossBatchCalibrator",
    "assemble_calibration_features",
    "calibrated_operating_point",
    "calibration_candidates",
    "equal_block_weights",
    "fit_cross_batch_calibrator",
    "paired_direction_gate",
    "select_boundary_candidates",
    "select_random_candidates",
    "audit_bpce_context",
    "collect_bpce_audit_contexts",
    "estimate_effect",
    "make_bpce_fixed_prefix",
    "make_bpce_paired_random_tapes",
    "sample_fixed_actions_with_uniforms",
    "summarize_bpce_semantics",
    "audit_short_horizon_context",
    "classify_component_label",
    "component_interval",
    "summarize_short_horizon_audit",
    "target_event_horizon",
    "validate_context_identity",
    "ActionSubstitutionOpportunityCostConfig",
    "OpportunityBranchTrace",
    "aggregate_target_rows",
    "audit_action_substitution_context",
    "intervention_is_unique",
    "reliable_positive_opportunity",
    "restore_probed_ammo",
    "summarize_action_substitution_audit",
    "ActionSubstitutionConfirmationConfig",
    "CostBranchTrace",
    "audit_confirmation_context",
    "collect_confirmation_contexts",
    "grouped_summary_rows",
    "summarize_confirmation",
    "validate_confirmation_contexts",
]
